# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbtproject'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbtproject'

# Global variables accessible across all dbt models via {{ var("variable_name") }}
vars:
  production_amount: 4

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  dbtproject:
    staging:
      +materialized: view
    marts:
      +materialized: table
    analytics:
      +materialized: view
    intermediate:
      +materialized: view