name: Pipeline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Pipeline:
    name: Setup Pipeline
    runs-on: [self-hosted, macOS, ARM64]
    defaults:
      run:
        working-directory: /Users/jonathankee/Data-Science-Projects
    steps:
      - name: Set current date
        run: echo "TODAY=$(date +'%d%m%Y')" >> $GITHUB_ENV

      - name: Create backup directory if missing
        run: mkdir -p ./backup_sql

      - name: backup
        run: docker exec -t postgres-container pg_dump -U postgres -d prosperous_universe > ./backup_sql/backup_${TODAY}.sql

      - name: Push backup to GitHub
        run: |
          ENCODED_CONTENT=$(base64 < ./backup_sql/backup_${TODAY}.sql | tr -d '\n')
          
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/contents/backup_sql/backup_${TODAY}.sql" \
            -d "{\"message\":\"chore: add database backup for ${TODAY}\",\"content\":\"${ENCODED_CONTENT}\"}"